### PR TITLE
Adding a pagination

### PR DESCRIPTION
**Pull request by ademkoc**
Hey there,

I'm adding a pagination to repositories releases results.

### CODE REVIEW

**Comment by Somsubhra** [comment]
Thanks for the patch!

**Comment by ErikMinekus** [comment]
`isLatestRelease` is now false unless the URL explicitly contains `page=1`.

**Comment by ErikMinekus** [comment]
Also, `Total Downloads` should count all releases, not just the releases on the current page.

**Comment by ademkoc** [comment]
Thank you @ErikMinekus, i made a new PR #50 for the latest release issue.

About total downloads, api gives us the count for each release not the total count. Before the pagination implementation each query result contained a maximum of 30 release and they were collecting. 

Shortly the calculation is made as much as the release displayed on the page.

**Comment by ErikMinekus** [comment]
Then I think the `Per page` options should be 10, 25, 50 and 100. Starting at 10 gives a more accurate Total Downloads count, and 100 is the maximum the GitHub API accepts.

**Pull request merged**
