### PR TITLE
feat: allow auto select and trigger get-stats-button after select

### PR DESCRIPTION
**Pull request by marceloavf**
For better accessibility, allow to auto search after user select one option with enter, tab or click action.

### CODE REVIEW

**Comment by tooomm** [comment]
What are this third party changes about?

Does this allow to hit <kbd>Enter</kbd> after entering a `github username` to jump to the `repo` field?

**Comment by marceloavf** [comment]
For now it doesn't, could be a great idea, it only trigger the button when you choose an option of repository, avoiding you to hit <kbd>Tab</kbd> and then <kbd>Enter</kbd> or using the `mouse`

> Before:

**1.** Type an username, <kbd>Tab</kbd>
**2.** Type an repository, choose one from the list using arrows, clicking or/and hitting <kbd>Enter</kbd>
**3.** Hit <kbd>Tab</kbd> and then <kbd>Enter</kbd> or click in the `button`

> Now:

**1.** Type an username, <kbd>Tab</kbd>
**2.** Type an repository, choose one from the list using arrows, clicking or/and hitting <kbd>Enter</kbd> and it automatically search it

---
[Demo link](https://rawgit.com/marceloavf/github-release-stats/master/index.html)

**Comment by tooomm** [comment]
>Now:
>1. Type an username, <kbd>Tab</kbd>
>2. Type an repository, choose one from the list using arrows, clicking or/and hitting <kbd>Enter</kbd> and it automatically search it

That's a huge improvement. No complains there.
But don't forget that any mobile device has no `Tab` button, that's why I double checked/suggested the <kbd>Enter</kbd> to make the jump from username to repo, too.

**Comment by marceloavf** [comment]
Great point, I did not think of that, I'll implement that!
Thanks!

**Comment by tooomm** [comment]
Tested with your demo link again - seems to work!

**Comment by Somsubhra** [comment]
Thanks for the patch!

**Pull request merged**
